---

- name: install locales packages
  apt: pkg={{item}} update_cache=yes install_recommends=no
  with_items:
    - locales

- name: create fake locales
  file:
    src: '/usr/share/i18n/locales/{{ item.src }}'
    dest: '/usr/share/i18n/locales/{{ item.dst }}'
    state: link
  with_items: locales_faked
  when: locales_faked is defined

- name: Add default locales
  lineinfile:
    dest=/var/lib/locales/supported.d/locale
    line='{{item}}'
    create=yes
    insertafter=EOF
  notify: Generate locales
  with_items: locales_supported

- name: link locale.gen configuration file
  file:
    path=/etc/locale.gen
    src=/var/lib/locales/supported.d/locale
    state=link
  notify: Generate locales
  
- meta: flush_handlers
