---

- name: install locales packages
  apt: pkg={{item}} update_cache=yes install_recommends=no cache_valid_time=3600
  with_items:
    - locales

- name: create fake locales
  file:
    src: '/usr/share/i18n/locales/{{ item.src }}'
    dest: '/usr/share/i18n/locales/{{ item.dst }}'
    state: link
  with_items: locales_faked
  when: locales_faked is defined

- include: ubuntu.yml
  when: ansible_lsb.id == 'Ubuntu'

- include: debian.yml
  when: ansible_lsb.id == 'Debian'
  
- meta: flush_handlers
